# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/mlpack

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/mlpack

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/mlpack/CMakeFiles /workspaces/mlpack/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/mlpack/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pkgconfig

# Build rule for target.
pkgconfig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pkgconfig
.PHONY : pkgconfig

# fast build rule for target.
pkgconfig/fast:
	$(MAKE) -f CMakeFiles/pkgconfig.dir/build.make CMakeFiles/pkgconfig.dir/build
.PHONY : pkgconfig/fast

#=============================================================================
# Target rules for targets named mlpack_gitversion

# Build rule for target.
mlpack_gitversion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_gitversion
.PHONY : mlpack_gitversion

# fast build rule for target.
mlpack_gitversion/fast:
	$(MAKE) -f CMakeFiles/mlpack_gitversion.dir/build.make CMakeFiles/mlpack_gitversion.dir/build
.PHONY : mlpack_gitversion/fast

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) -f CMakeFiles/distclean.dir/build.make CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

#=============================================================================
# Target rules for targets named mlpack_test

# Build rule for target.
mlpack_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_test
.PHONY : mlpack_test

# fast build rule for target.
mlpack_test/fast:
	$(MAKE) -f src/mlpack/CMakeFiles/mlpack_test.dir/build.make src/mlpack/CMakeFiles/mlpack_test.dir/build
.PHONY : mlpack_test/fast

#=============================================================================
# Target rules for targets named mlpack_range_search

# Build rule for target.
mlpack_range_search: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_range_search
.PHONY : mlpack_range_search

# fast build rule for target.
mlpack_range_search/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_range_search.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_range_search.dir/build
.PHONY : mlpack_range_search/fast

#=============================================================================
# Target rules for targets named mlpack_sparse_coding

# Build rule for target.
mlpack_sparse_coding: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_sparse_coding
.PHONY : mlpack_sparse_coding

# fast build rule for target.
mlpack_sparse_coding/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_sparse_coding.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_sparse_coding.dir/build
.PHONY : mlpack_sparse_coding/fast

#=============================================================================
# Target rules for targets named mlpack_random_forest

# Build rule for target.
mlpack_random_forest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_random_forest
.PHONY : mlpack_random_forest

# fast build rule for target.
mlpack_random_forest/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_random_forest.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_random_forest.dir/build
.PHONY : mlpack_random_forest/fast

#=============================================================================
# Target rules for targets named mlpack_adaboost

# Build rule for target.
mlpack_adaboost: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_adaboost
.PHONY : mlpack_adaboost

# fast build rule for target.
mlpack_adaboost/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_adaboost.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_adaboost.dir/build
.PHONY : mlpack_adaboost/fast

#=============================================================================
# Target rules for targets named mlpack_radical

# Build rule for target.
mlpack_radical: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_radical
.PHONY : mlpack_radical

# fast build rule for target.
mlpack_radical/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_radical.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_radical.dir/build
.PHONY : mlpack_radical/fast

#=============================================================================
# Target rules for targets named mlpack_preprocess_one_hot_encoding

# Build rule for target.
mlpack_preprocess_one_hot_encoding: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_preprocess_one_hot_encoding
.PHONY : mlpack_preprocess_one_hot_encoding

# fast build rule for target.
mlpack_preprocess_one_hot_encoding/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_preprocess_one_hot_encoding.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_preprocess_one_hot_encoding.dir/build
.PHONY : mlpack_preprocess_one_hot_encoding/fast

#=============================================================================
# Target rules for targets named mlpack_preprocess_binarize

# Build rule for target.
mlpack_preprocess_binarize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_preprocess_binarize
.PHONY : mlpack_preprocess_binarize

# fast build rule for target.
mlpack_preprocess_binarize/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_preprocess_binarize.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_preprocess_binarize.dir/build
.PHONY : mlpack_preprocess_binarize/fast

#=============================================================================
# Target rules for targets named mlpack_preprocess_split

# Build rule for target.
mlpack_preprocess_split: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_preprocess_split
.PHONY : mlpack_preprocess_split

# fast build rule for target.
mlpack_preprocess_split/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_preprocess_split.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_preprocess_split.dir/build
.PHONY : mlpack_preprocess_split/fast

#=============================================================================
# Target rules for targets named mlpack_preprocess_describe

# Build rule for target.
mlpack_preprocess_describe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_preprocess_describe
.PHONY : mlpack_preprocess_describe

# fast build rule for target.
mlpack_preprocess_describe/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_preprocess_describe.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_preprocess_describe.dir/build
.PHONY : mlpack_preprocess_describe/fast

#=============================================================================
# Target rules for targets named mlpack_perceptron

# Build rule for target.
mlpack_perceptron: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_perceptron
.PHONY : mlpack_perceptron

# fast build rule for target.
mlpack_perceptron/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_perceptron.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_perceptron.dir/build
.PHONY : mlpack_perceptron/fast

#=============================================================================
# Target rules for targets named mlpack_pca

# Build rule for target.
mlpack_pca: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_pca
.PHONY : mlpack_pca

# fast build rule for target.
mlpack_pca/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_pca.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_pca.dir/build
.PHONY : mlpack_pca/fast

#=============================================================================
# Target rules for targets named mlpack_linear_regression

# Build rule for target.
mlpack_linear_regression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_linear_regression
.PHONY : mlpack_linear_regression

# fast build rule for target.
mlpack_linear_regression/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_linear_regression.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_linear_regression.dir/build
.PHONY : mlpack_linear_regression/fast

#=============================================================================
# Target rules for targets named mlpack_nmf

# Build rule for target.
mlpack_nmf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_nmf
.PHONY : mlpack_nmf

# fast build rule for target.
mlpack_nmf/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_nmf.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_nmf.dir/build
.PHONY : mlpack_nmf/fast

#=============================================================================
# Target rules for targets named mlpack_kfn

# Build rule for target.
mlpack_kfn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_kfn
.PHONY : mlpack_kfn

# fast build rule for target.
mlpack_kfn/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_kfn.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_kfn.dir/build
.PHONY : mlpack_kfn/fast

#=============================================================================
# Target rules for targets named mlpack_preprocess_imputer

# Build rule for target.
mlpack_preprocess_imputer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_preprocess_imputer
.PHONY : mlpack_preprocess_imputer

# fast build rule for target.
mlpack_preprocess_imputer/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_preprocess_imputer.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_preprocess_imputer.dir/build
.PHONY : mlpack_preprocess_imputer/fast

#=============================================================================
# Target rules for targets named mlpack_hmm_generate

# Build rule for target.
mlpack_hmm_generate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_hmm_generate
.PHONY : mlpack_hmm_generate

# fast build rule for target.
mlpack_hmm_generate/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_hmm_generate.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_hmm_generate.dir/build
.PHONY : mlpack_hmm_generate/fast

#=============================================================================
# Target rules for targets named mlpack_preprocess_scale

# Build rule for target.
mlpack_preprocess_scale: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_preprocess_scale
.PHONY : mlpack_preprocess_scale

# fast build rule for target.
mlpack_preprocess_scale/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_preprocess_scale.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_preprocess_scale.dir/build
.PHONY : mlpack_preprocess_scale/fast

#=============================================================================
# Target rules for targets named mlpack_knn

# Build rule for target.
mlpack_knn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_knn
.PHONY : mlpack_knn

# fast build rule for target.
mlpack_knn/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_knn.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_knn.dir/build
.PHONY : mlpack_knn/fast

#=============================================================================
# Target rules for targets named mlpack_hmm_train

# Build rule for target.
mlpack_hmm_train: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_hmm_train
.PHONY : mlpack_hmm_train

# fast build rule for target.
mlpack_hmm_train/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_hmm_train.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_hmm_train.dir/build
.PHONY : mlpack_hmm_train/fast

#=============================================================================
# Target rules for targets named mlpack_gmm_generate

# Build rule for target.
mlpack_gmm_generate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_gmm_generate
.PHONY : mlpack_gmm_generate

# fast build rule for target.
mlpack_gmm_generate/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_gmm_generate.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_gmm_generate.dir/build
.PHONY : mlpack_gmm_generate/fast

#=============================================================================
# Target rules for targets named mlpack_logistic_regression

# Build rule for target.
mlpack_logistic_regression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_logistic_regression
.PHONY : mlpack_logistic_regression

# fast build rule for target.
mlpack_logistic_regression/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_logistic_regression.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_logistic_regression.dir/build
.PHONY : mlpack_logistic_regression/fast

#=============================================================================
# Target rules for targets named mlpack_decision_tree

# Build rule for target.
mlpack_decision_tree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_decision_tree
.PHONY : mlpack_decision_tree

# fast build rule for target.
mlpack_decision_tree/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_decision_tree.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_decision_tree.dir/build
.PHONY : mlpack_decision_tree/fast

#=============================================================================
# Target rules for targets named mlpack_kernel_pca

# Build rule for target.
mlpack_kernel_pca: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_kernel_pca
.PHONY : mlpack_kernel_pca

# fast build rule for target.
mlpack_kernel_pca/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_kernel_pca.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_kernel_pca.dir/build
.PHONY : mlpack_kernel_pca/fast

#=============================================================================
# Target rules for targets named mlpack_kde

# Build rule for target.
mlpack_kde: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_kde
.PHONY : mlpack_kde

# fast build rule for target.
mlpack_kde/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_kde.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_kde.dir/build
.PHONY : mlpack_kde/fast

#=============================================================================
# Target rules for targets named mlpack_linear_svm

# Build rule for target.
mlpack_linear_svm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_linear_svm
.PHONY : mlpack_linear_svm

# fast build rule for target.
mlpack_linear_svm/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_linear_svm.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_linear_svm.dir/build
.PHONY : mlpack_linear_svm/fast

#=============================================================================
# Target rules for targets named mlpack_dbscan

# Build rule for target.
mlpack_dbscan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_dbscan
.PHONY : mlpack_dbscan

# fast build rule for target.
mlpack_dbscan/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_dbscan.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_dbscan.dir/build
.PHONY : mlpack_dbscan/fast

#=============================================================================
# Target rules for targets named mlpack_lmnn

# Build rule for target.
mlpack_lmnn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_lmnn
.PHONY : mlpack_lmnn

# fast build rule for target.
mlpack_lmnn/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_lmnn.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_lmnn.dir/build
.PHONY : mlpack_lmnn/fast

#=============================================================================
# Target rules for targets named mlpack_bayesian_linear_regression

# Build rule for target.
mlpack_bayesian_linear_regression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_bayesian_linear_regression
.PHONY : mlpack_bayesian_linear_regression

# fast build rule for target.
mlpack_bayesian_linear_regression/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_bayesian_linear_regression.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_bayesian_linear_regression.dir/build
.PHONY : mlpack_bayesian_linear_regression/fast

#=============================================================================
# Target rules for targets named mlpack_gmm_train

# Build rule for target.
mlpack_gmm_train: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_gmm_train
.PHONY : mlpack_gmm_train

# fast build rule for target.
mlpack_gmm_train/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_gmm_train.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_gmm_train.dir/build
.PHONY : mlpack_gmm_train/fast

#=============================================================================
# Target rules for targets named mlpack_local_coordinate_coding

# Build rule for target.
mlpack_local_coordinate_coding: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_local_coordinate_coding
.PHONY : mlpack_local_coordinate_coding

# fast build rule for target.
mlpack_local_coordinate_coding/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_local_coordinate_coding.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_local_coordinate_coding.dir/build
.PHONY : mlpack_local_coordinate_coding/fast

#=============================================================================
# Target rules for targets named mlpack_krann

# Build rule for target.
mlpack_krann: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_krann
.PHONY : mlpack_krann

# fast build rule for target.
mlpack_krann/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_krann.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_krann.dir/build
.PHONY : mlpack_krann/fast

#=============================================================================
# Target rules for targets named mlpack_gmm_probability

# Build rule for target.
mlpack_gmm_probability: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_gmm_probability
.PHONY : mlpack_gmm_probability

# fast build rule for target.
mlpack_gmm_probability/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_gmm_probability.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_gmm_probability.dir/build
.PHONY : mlpack_gmm_probability/fast

#=============================================================================
# Target rules for targets named mlpack_cf

# Build rule for target.
mlpack_cf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_cf
.PHONY : mlpack_cf

# fast build rule for target.
mlpack_cf/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_cf.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_cf.dir/build
.PHONY : mlpack_cf/fast

#=============================================================================
# Target rules for targets named mlpack_approx_kfn

# Build rule for target.
mlpack_approx_kfn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_approx_kfn
.PHONY : mlpack_approx_kfn

# fast build rule for target.
mlpack_approx_kfn/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_approx_kfn.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_approx_kfn.dir/build
.PHONY : mlpack_approx_kfn/fast

#=============================================================================
# Target rules for targets named mlpack_softmax_regression

# Build rule for target.
mlpack_softmax_regression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_softmax_regression
.PHONY : mlpack_softmax_regression

# fast build rule for target.
mlpack_softmax_regression/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_softmax_regression.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_softmax_regression.dir/build
.PHONY : mlpack_softmax_regression/fast

#=============================================================================
# Target rules for targets named mlpack_emst

# Build rule for target.
mlpack_emst: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_emst
.PHONY : mlpack_emst

# fast build rule for target.
mlpack_emst/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_emst.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_emst.dir/build
.PHONY : mlpack_emst/fast

#=============================================================================
# Target rules for targets named mlpack_hmm_loglik

# Build rule for target.
mlpack_hmm_loglik: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_hmm_loglik
.PHONY : mlpack_hmm_loglik

# fast build rule for target.
mlpack_hmm_loglik/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_hmm_loglik.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_hmm_loglik.dir/build
.PHONY : mlpack_hmm_loglik/fast

#=============================================================================
# Target rules for targets named mlpack_hmm_viterbi

# Build rule for target.
mlpack_hmm_viterbi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_hmm_viterbi
.PHONY : mlpack_hmm_viterbi

# fast build rule for target.
mlpack_hmm_viterbi/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_hmm_viterbi.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_hmm_viterbi.dir/build
.PHONY : mlpack_hmm_viterbi/fast

#=============================================================================
# Target rules for targets named mlpack_hoeffding_tree

# Build rule for target.
mlpack_hoeffding_tree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_hoeffding_tree
.PHONY : mlpack_hoeffding_tree

# fast build rule for target.
mlpack_hoeffding_tree/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_hoeffding_tree.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_hoeffding_tree.dir/build
.PHONY : mlpack_hoeffding_tree/fast

#=============================================================================
# Target rules for targets named mlpack_image_converter

# Build rule for target.
mlpack_image_converter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_image_converter
.PHONY : mlpack_image_converter

# fast build rule for target.
mlpack_image_converter/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_image_converter.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_image_converter.dir/build
.PHONY : mlpack_image_converter/fast

#=============================================================================
# Target rules for targets named mlpack_kmeans

# Build rule for target.
mlpack_kmeans: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_kmeans
.PHONY : mlpack_kmeans

# fast build rule for target.
mlpack_kmeans/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_kmeans.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_kmeans.dir/build
.PHONY : mlpack_kmeans/fast

#=============================================================================
# Target rules for targets named mlpack_lars

# Build rule for target.
mlpack_lars: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_lars
.PHONY : mlpack_lars

# fast build rule for target.
mlpack_lars/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_lars.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_lars.dir/build
.PHONY : mlpack_lars/fast

#=============================================================================
# Target rules for targets named mlpack_lsh

# Build rule for target.
mlpack_lsh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_lsh
.PHONY : mlpack_lsh

# fast build rule for target.
mlpack_lsh/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_lsh.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_lsh.dir/build
.PHONY : mlpack_lsh/fast

#=============================================================================
# Target rules for targets named mlpack_fastmks

# Build rule for target.
mlpack_fastmks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_fastmks
.PHONY : mlpack_fastmks

# fast build rule for target.
mlpack_fastmks/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_fastmks.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_fastmks.dir/build
.PHONY : mlpack_fastmks/fast

#=============================================================================
# Target rules for targets named mlpack_nbc

# Build rule for target.
mlpack_nbc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_nbc
.PHONY : mlpack_nbc

# fast build rule for target.
mlpack_nbc/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_nbc.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_nbc.dir/build
.PHONY : mlpack_nbc/fast

#=============================================================================
# Target rules for targets named mlpack_mean_shift

# Build rule for target.
mlpack_mean_shift: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_mean_shift
.PHONY : mlpack_mean_shift

# fast build rule for target.
mlpack_mean_shift/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_mean_shift.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_mean_shift.dir/build
.PHONY : mlpack_mean_shift/fast

#=============================================================================
# Target rules for targets named mlpack_det

# Build rule for target.
mlpack_det: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_det
.PHONY : mlpack_det

# fast build rule for target.
mlpack_det/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_det.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_det.dir/build
.PHONY : mlpack_det/fast

#=============================================================================
# Target rules for targets named mlpack_nca

# Build rule for target.
mlpack_nca: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlpack_nca
.PHONY : mlpack_nca

# fast build rule for target.
mlpack_nca/fast:
	$(MAKE) -f src/mlpack/methods/CMakeFiles/mlpack_nca.dir/build.make src/mlpack/methods/CMakeFiles/mlpack_nca.dir/build
.PHONY : mlpack_nca/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... pkgconfig"
	@echo "... mlpack_gitversion"
	@echo "... distclean"
	@echo "... mlpack_test"
	@echo "... mlpack_range_search"
	@echo "... mlpack_sparse_coding"
	@echo "... mlpack_random_forest"
	@echo "... mlpack_adaboost"
	@echo "... mlpack_radical"
	@echo "... mlpack_preprocess_one_hot_encoding"
	@echo "... mlpack_preprocess_binarize"
	@echo "... mlpack_preprocess_split"
	@echo "... mlpack_preprocess_describe"
	@echo "... mlpack_perceptron"
	@echo "... mlpack_pca"
	@echo "... mlpack_linear_regression"
	@echo "... mlpack_nmf"
	@echo "... mlpack_kfn"
	@echo "... mlpack_preprocess_imputer"
	@echo "... mlpack_hmm_generate"
	@echo "... mlpack_preprocess_scale"
	@echo "... mlpack_knn"
	@echo "... mlpack_hmm_train"
	@echo "... mlpack_gmm_generate"
	@echo "... mlpack_logistic_regression"
	@echo "... mlpack_decision_tree"
	@echo "... mlpack_kernel_pca"
	@echo "... mlpack_kde"
	@echo "... mlpack_linear_svm"
	@echo "... mlpack_dbscan"
	@echo "... mlpack_lmnn"
	@echo "... mlpack_bayesian_linear_regression"
	@echo "... mlpack_gmm_train"
	@echo "... mlpack_local_coordinate_coding"
	@echo "... mlpack_krann"
	@echo "... mlpack_gmm_probability"
	@echo "... mlpack_cf"
	@echo "... mlpack_approx_kfn"
	@echo "... mlpack_softmax_regression"
	@echo "... mlpack_emst"
	@echo "... mlpack_hmm_loglik"
	@echo "... mlpack_hmm_viterbi"
	@echo "... mlpack_hoeffding_tree"
	@echo "... mlpack_image_converter"
	@echo "... mlpack_kmeans"
	@echo "... mlpack_lars"
	@echo "... mlpack_lsh"
	@echo "... mlpack_fastmks"
	@echo "... mlpack_nbc"
	@echo "... mlpack_mean_shift"
	@echo "... mlpack_det"
	@echo "... mlpack_nca"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

